### ISSUE TITLE
string alignment doesn't work

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/lineupjs#91]
* Release number or git hash: 3.1.5
 * Web browser version and OS: chrome

### Steps to reproduce

 1. create a string column with `alignment: right`

### Observed behavior
 * text is still on the left

missing rules:
```css
.lu-right {
  justify-content: flex-end;
  text-align: right;
}
.lu-center {
  justify-content: center;
  text-align: left;
}
```
